#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul  8 11:04:01 2022

@author: stefano
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
#import os
#path = '/home/stefano/perceptron'
#os.chdir(path)
fileName = 'dataFlowers.xlsx'
df = pd.read_excel(fileName, header = None)